services:
  db:
    image: postgres:15
    container_name: repforce_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - repforce_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: repforce_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    networks:
      - repforce_net

  frontend-web:
    build:
      context: ./frontend-web
      args:
        - REACT_APP_API_URL=/api
      dockerfile: Dockerfile
    container_name: repforce_frontend
    ports:
      - "3000:80"
    networks:
      - repforce_net
    depends_on:
      - backend

networks:
  repforce_net:
    driver: bridge

volumes:
  postgres-data: