services:
  db:
    image: postgres:15
    container_name: repforce_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    
    # AQUI: O Docker Compose vai ler o arquivo .env na pasta raiz
    # e injetar as variáveis (POSTGRES_USER, etc.) neste contêiner.
    env_file:
      - .env
    networks:
      - repforce_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: repforce_backend
    
    # REMOVIDO: O '--reload' não deve ser usado em produção.
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    
    volumes:
      - ./backend:/app
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
      
    # AQUI: Injeta as variáveis do .env (SECRET_KEY, ALGORITHM, etc.)
    env_file:
      - .env
      
    # AQUI: Construímos a DATABASE_URL usando as variáveis
    # que foram injetadas do .env.
    environment:
      DATABASE_URL: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    networks:
      - repforce_net

  frontend-web:
    build:
      context: ./frontend-web
      dockerfile: Dockerfile
    container_name: repforce_frontend
    ports:
      - "127.0.0.1:3000:80"
    networks:
      - repforce_net

networks:
  repforce_net:
    driver: bridge

volumes:
  postgres-data: